### ISSUE TITLE
Data dupplicated after run for 10-12 hour

### ISSUE THREAD

**Issue by siravijbb** [KNACKSAT2-TGPS/KNACKSAT2-TGPS-Code#7]
https://github.com/KNACKSAT2-TGPS/KNACKSAT2-TGPS-Code/blob/76462bb8a7f4b309d7a28cba74c134740a404f05/TGPS%20SIMULATION%20MASTER/TGPS_SIMULATION_MASTER.ino#L139-L284

**Comment by siravijbb** [comment]
![image](https://github.com/KNACKSAT2-TGPS/KNACKSAT2-TGPS-Code/assets/47503079/a461d4a0-c9e3-47e9-853f-c49fc6591bf2)

**Comment by PL7MX0** [comment]
The program doesn't have any problem.😉
